const fs = require('fs');
const path = require('path');

const DATA_DIR = path.resolve(__dirname, '../public/data');

/**
 * 법정 교사 배치기준 (영유아보육법 시행규칙)
 * ageRange의 최소 연령을 기준으로 가장 엄격한 법정 비율 적용
 *
 * 만 0세 미만(0세): 3:1 / 만 1세: 5:1 / 만 2세: 7:1
 * 만 3세: 15:1 / 만 4세 이상: 20:1 / 방과후(취학): 20:1
 *
 * 혼합 연령의 경우 가장 어린 연령의 기준 적용
 */
function getLegalRatioThreshold(ageRange, specialPrograms) {
    // 방과후 전담 어린이집 (취학아동 20:1)
    if ((specialPrograms || '').includes('방과후')) return 20;

    const minAgeMatch = (ageRange || '').match(/만\s*(\d)세/);
    const minAge = minAgeMatch ? parseInt(minAgeMatch[1]) : 2; // 기본값 2세(7:1)

    if (minAge === 0) return 5;  // 0세 포함: 3:1이 원칙이나 혼합 현실 반영해 5 적용
    if (minAge === 1) return 5;  // 1세: 5:1
    if (minAge === 2) return 7;  // 2세: 7:1
    if (minAge === 3) return 15; // 3세: 15:1
    return 20;                   // 4세 이상: 20:1
}

function calculateStabilityScore(inst) {
    let score = 3.0;

    // 1. 법정 교사 배치 기준 준수 여부 (어린이집)
    if (inst.source === '어린이집' && inst.childrenPerTeacher > 0) {
        const threshold = getLegalRatioThreshold(inst.ageRange, inst.specialPrograms);
        const ratio = inst.childrenPerTeacher;
        if (ratio <= threshold * 0.6) score += 1.0;       // 기준 60% 이하 → 우수
        else if (ratio <= threshold * 0.85) score += 0.5; // 기준 85% 이하 → 양호
        else if (ratio > threshold) score -= 1.0;         // 기준 초과 → 감점
    }

    // 1-b. 유치원 교사 비율
    if (inst.source === '유치원' && inst.childrenPerTeacher > 0) {
        const ratio = inst.childrenPerTeacher;
        if (ratio <= 8) score += 1.0;
        else if (ratio <= 12) score += 0.5;
        else if (ratio > 20) score -= 1.0;
    }

    // 2. 교사 근속 연수 (오래될수록 좋음)
    if (inst.teacherTenure) {
        const t = inst.teacherTenure;
        const total = (t.under1 || 0) + (t.year1to2 || 0) + (t.year2to4 || 0) + (t.year4to6 || 0) + (t.over6 || 0);
        if (total > 0) {
            const experiencedRatio = ((t.year4to6 || 0) + (t.over6 || 0)) / total;
            if (experiencedRatio >= 0.5) score += 1.0;
            else if (experiencedRatio >= 0.3) score += 0.5;
            else if (experiencedRatio < 0.1) score -= 0.5;
        }
    }

    // 3. CCTV 설치 여부 (어린이집)
    if (inst.source === '어린이집' && inst.cctvCount > 0) score += 0.3;

    // 4. 대기자 없음 (어린이집) — 입소 가능성 높음
    if (inst.source === '어린이집' && inst.waitlistTotal === 0 && inst.capacity > 0) score += 0.2;

    // 5. 영양사 법정 의무 미달 (100인 이상) — 감점
    if (inst.capacity >= 100 && !(inst.mealStatus || '').includes('영양사')) score -= 0.5;

    // 6. CCTV 미설치 (어린이집) — 감점
    if (inst.source === '어린이집') {
        const hasCctv = (inst.cctvCount != null && inst.cctvCount > 0) ||
                        (inst.safetyStatus || '').includes('CCTV');
        if (!hasCctv) score -= 0.3;
    }

    return Math.min(5, Math.max(1, Math.round(score * 10) / 10));
}

function augmentData() {
    const files = fs.readdirSync(DATA_DIR).filter(f => f.endsWith('.json') && f !== 'regions.json');
    console.log(`🔍 Processing ${files.length} data files...`);

    let totalInst = 0, improved = { ageRange: 0, expenseLevel: 0, operatingHours: 0, mealStatus: 0, tags: 0, alimiUrl: 0 };

    files.forEach(file => {
        const filePath = path.join(DATA_DIR, file);
        const data = JSON.parse(fs.readFileSync(filePath, 'utf-8'));

        const augmented = data.map(inst => {
            // 1. 연령 범위 (ageRange) 추론
            if (inst.ageRange === '-' || !inst.ageRange) {
                if (inst.source === '유치원') {
                    inst.ageRange = '만 3세 ~ 5세';
                } else {
                    // 어린이집: capacity 크기로 추정 (0세반 없으면 0~2세 제외)
                    inst.ageRange = '만 0세 ~ 5세';
                }
                improved.ageRange++;
            }

            // 2. 비용 수준 (expenseLevel) 추론
            if (inst.expenseLevel === '-' || !inst.expenseLevel) {
                if (inst.type === '국공립') {
                    inst.expenseLevel = inst.source === '유치원'
                        ? '무상교육 (누리과정 지원)'
                        : '정부 지원 (보육료 지원)';
                } else if (inst.type === '사회복지법인' || inst.type === '법인단체') {
                    inst.expenseLevel = '정부 지원 (표준 보육료)';
                } else if (inst.type === '가정' || inst.type === '부모협동') {
                    inst.expenseLevel = '정부 지원 (보육료 지원)';
                } else if (inst.type === '직장') {
                    inst.expenseLevel = '직장 지원 + 정부 보조';
                } else {
                    // 사립, 민간
                    inst.expenseLevel = '시설별 차등 (상세 문의)';
                }
                improved.expenseLevel++;
            }

            // 3. 운영 시간 (operatingHours) 추론
            const isAutoGenerated = /\(기본\)|\(직장 어린이집 기준\)/.test(inst.operatingHours || '');
            if (inst.source === '어린이집' && (inst.operatingHours === '-' || !inst.operatingHours || isAutoGenerated)) {
                const programs = inst.specialPrograms || '';
                const tags = inst.tags || [];
                const isNight = programs.includes('야간연장') || tags.includes('야간운영');
                const is24h = programs.includes('24시간') || tags.includes('24시간');
                if (is24h) {
                    inst.operatingHours = '24시간';
                } else if (isNight) {
                    inst.operatingHours = '평일기준시간 : 07:30 ~ 24:00 (야간연장)';
                } else if (inst.type === '직장') {
                    inst.operatingHours = '평일기준시간 : 07:30 ~ 19:30';
                } else {
                    inst.operatingHours = '평일기준시간 : 07:30 ~ 19:30';
                }
                improved.operatingHours++;
            }

            // 4. 급식 현황 (mealStatus) 보완 — 어린이집에서 영양사 없어도 급식 제공
            if (inst.source === '어린이집' && (inst.mealStatus === '-' || !inst.mealStatus)) {
                if (inst.capacity >= 100) {
                    inst.mealStatus = '자체 급식 (영양사 배치 권고 규모)';
                } else {
                    inst.mealStatus = '급식 제공 (영양사 미배치)';
                }
                improved.mealStatus++;
            }

            // 5. 태그 (tags) 동적 생성
            const prevTagCount = (inst.tags || []).length;
            const tags = new Set(inst.tags || []);

            // 교통
            if (inst.hasSchoolBus) tags.add(inst.source === '어린이집' ? '통학차량' : '셔틀운행');

            // 규모
            if (inst.capacity >= 100) tags.add('대규모시설');
            else if (inst.capacity < 30) tags.add('소규모시설');

            // CCTV
            const safety = inst.safetyStatus || '';
            if (safety.includes('CCTV') || (inst.cctvCount != null && inst.cctvCount > 0)) tags.add('CCTV완비');

            // 입소 대기
            if (inst.source === '어린이집') {
                if (inst.waitlistTotal != null && inst.waitlistTotal > 0) tags.add('대기있음');
                else if (inst.waitlistTotal === 0) tags.add('즉시입소가능');
            }

            // 정원 여유 (현원/정원 < 80%)
            if (inst.capacity > 0 && inst.currentPupils > 0) {
                const fillRate = inst.currentPupils / inst.capacity;
                if (fillRate <= 0.8) tags.add('정원여유');
                else if (fillRate >= 0.97) tags.add('거의만원');
            }

            // 특성화 프로그램
            const programs = inst.specialPrograms || '';
            if (programs.includes('야간연장')) tags.add('야간연장');
            if (programs.includes('장애아')) tags.add('장애아통합');
            if (programs.includes('방과후')) tags.add('방과후운영');
            if (programs.includes('영어')) tags.add('영어교육');
            if (programs.includes('체육') || programs.includes('스포츠')) tags.add('체육특성화');
            if (programs !== '-' && programs !== '일반' && programs !== '' && programs.length > 2) tags.add('특성화교육');

            // 급식
            if (inst.mealStatus && inst.mealStatus.includes('영양사')) tags.add('영양사배치');

            // 법정 교사 배치기준 준수 여부 태그 (어린이집)
            if (inst.source === '어린이집' && inst.childrenPerTeacher > 0) {
                const threshold = getLegalRatioThreshold(inst.ageRange, inst.specialPrograms);
                const ratio = inst.childrenPerTeacher;
                if (ratio <= threshold * 0.6) tags.add('교사비율우수');
                else if (ratio > threshold) tags.add('교사비율주의');
            }

            // 숙련 교사
            if (inst.teacherTenure) {
                const t = inst.teacherTenure;
                const total = (t.under1 || 0) + (t.year1to2 || 0) + (t.year2to4 || 0) + (t.year4to6 || 0) + (t.over6 || 0);
                if (total > 0 && ((t.year4to6 || 0) + (t.over6 || 0)) / total >= 0.4) {
                    tags.add('숙련교사');
                }
            }

            // 법적 기준 비교 태그
            // 영양사 법정 의무: 100인 이상 시설 필수 (영유아보육법 시행규칙 제23조)
            if (inst.capacity >= 100) {
                const hasNutri = (inst.mealStatus || '').includes('영양사');
                if (hasNutri) tags.add('영양사법정충족');
                else tags.add('영양사법정미달');
            }

            // CCTV 설치 의무: 모든 어린이집 (영유아보육법 제15조의4)
            if (inst.source === '어린이집') {
                const hasCctv = (inst.cctvCount != null && inst.cctvCount > 0) ||
                                (inst.safetyStatus || '').includes('CCTV');
                if (!hasCctv) tags.add('CCTV미설치');
            }

            inst.tags = Array.from(tags);
            if (inst.tags.length > prevTagCount) improved.tags++;

            // 6. 어린이집 alimiUrl 보정
            if (inst.source === '어린이집') {
                const url = inst.alimiUrl || '';

                // 알려진 도메인 오타 교정
                let corrected = url
                    .replace(/https?:\/\/cafedaum\.net\//i,  'http://cafe.daum.net/')
                    .replace(/https?:\/\/cafenaver\.com\//i, 'http://cafe.naver.com/')
                    .replace(/([a-z]{2,})\.\//gi, '$1/');

                // 이전 childcare.go.kr URL → 어린이집 알리미 URL로 교체
                const oldPortalMatch = corrected.match(/childcare\.go\.kr.*[?&]stcode=(\d+)/i);
                if (oldPortalMatch) {
                    corrected = `https://info.childcare.go.kr/info_html5/pnis/search/preview/SummaryInfoSlPu.jsp?flag=YJ&STCODE_POP=${oldPortalMatch[1]}`;
                }
                // iseoul.seoul.go.kr → 어린이집 알리미 URL로 교체 (stcode 불일치 있어 id 우선 사용)
                if (corrected.includes('iseoul') && inst.id && /^\d{11,}$/.test(inst.id)) {
                    corrected = `https://info.childcare.go.kr/info_html5/pnis/search/preview/SummaryInfoSlPu.jsp?flag=YJ&STCODE_POP=${inst.id}`;
                }
                // 기존 STCODE_POP URL에 flag=YJ 누락된 경우 보완
                if (corrected.includes('STCODE_POP=') && !corrected.includes('flag=YJ')) {
                    corrected = corrected.replace('STCODE_POP=', 'flag=YJ&STCODE_POP=');
                }

                if (corrected !== url) {
                    inst.alimiUrl = corrected;
                    improved.alimiUrl++;
                }

                // 링크 없는 어린이집 → 어린이집 알리미 공시 URL (stcode = id)
                if (!inst.alimiUrl && inst.id && /^\d{11,}$/.test(inst.id)) {
                    inst.alimiUrl = `https://info.childcare.go.kr/info_html5/pnis/search/preview/SummaryInfoSlPu.jsp?flag=YJ&STCODE_POP=${inst.id}`;
                    improved.alimiUrl++;
                }
            }

            // 7. 안정성 점수
            inst.stabilityScore = calculateStabilityScore(inst);

            totalInst++;
            return inst;
        });

        fs.writeFileSync(filePath, JSON.stringify(augmented, null, 2), 'utf-8');
    });

    console.log(`\n✅ Data augmentation complete! (총 ${totalInst}개 기관)`);
    console.log(`   ageRange 보정:      ${improved.ageRange}건`);
    console.log(`   expenseLevel 보정:  ${improved.expenseLevel}건`);
    console.log(`   operatingHours 보정:${improved.operatingHours}건`);
    console.log(`   mealStatus 보정:    ${improved.mealStatus}건`);
    console.log(`   tags 추가/보완:     ${improved.tags}건`);
    console.log(`   alimiUrl 보정/생성: ${improved.alimiUrl}건`);
}

augmentData();
